version: 2
jobs:
  build:
    machine:
      image: 'circleci/classic:latest'
      docker_layer_caching: true
    environment:
      IMAGE_REPO: 'mozamimy/lambda-slack-notify-ci'
    steps:
      - checkout
      - run:
          name: 'Build container image'
          command: |
            docker pull $IMAGE_REPO:latest || true
            docker build -t $IMAGE_REPO --cache-from $IMAGE_REPO:latest .
      - run:
          name: 'Push image'
          command: |
            docker login -u $DOCKER_REG_USER  -p $DOCKER_REG_PASSWORD
            docker push $IMAGE_REPO:latest
      - run:
          name: 'Cargo fmt'
          command: |
            docker run -v $PWD:/workspace $IMAGE_REPO cargo fmt --all -- --check
